// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/register" | "/login" | "/blogs" | "/blog/:slug" | "/*";
  };
  "pages/Home/Home.jsx": {
    id: "pages/Home/Home";
    page: "/";
  };
  "pages/About/About.jsx": {
    id: "pages/About/About";
    page: "/about";
  };
  "pages/Register/Register.jsx": {
    id: "pages/Register/Register";
    page: "/register";
  };
  "pages/LogIn/LogIn.jsx": {
    id: "pages/LogIn/LogIn";
    page: "/login";
  };
  "pages/Blogs/Blogs.jsx": {
    id: "pages/Blogs/Blogs";
    page: "/blogs";
  };
  "pages/BlogDetails/BlogDetails.jsx": {
    id: "pages/BlogDetails/BlogDetails";
    page: "/blog/:slug";
  };
  "pages/PageNotFound/PageNotFound.jsx": {
    id: "pages/PageNotFound/PageNotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/Home/Home": typeof import("./src/pages/Home/Home.jsx");
  "pages/About/About": typeof import("./src/pages/About/About.jsx");
  "pages/Register/Register": typeof import("./src/pages/Register/Register.jsx");
  "pages/LogIn/LogIn": typeof import("./src/pages/LogIn/LogIn.jsx");
  "pages/Blogs/Blogs": typeof import("./src/pages/Blogs/Blogs.jsx");
  "pages/BlogDetails/BlogDetails": typeof import("./src/pages/BlogDetails/BlogDetails.jsx");
  "pages/PageNotFound/PageNotFound": typeof import("./src/pages/PageNotFound/PageNotFound.jsx");
};